BOT_TOKEN = '5470903180:AAGDwjvq_Bf3jY8ymrBbC_Uzg9lzq_aUSxI'
API_ID = '19919438'
API_HASH = 'c6ef54eb0cdd29441ae33921531cb4e8'


# DATOS DEL MOODLE
#USUARIO DEL MOODLE entre las comillas
USUARIO = 'leonelmg'
#CONTRASEÑA DEL MOODLE entre las comillas
PASSWORD = 'Jose9101*'
#ID DEL MOODLE
USUARIO_ID = 7463
# PAGINA DEL MOODLE DEBE ESTAR COMO EL EJEMPLO: cursos.edu.uo.cu
MOODLE_URL = 'aula.ensap.sld.cu'
#TAMAÑO EN LO QUE SE PICARAN LOS ZIP AL SUBIR AL MOODLE
ZIP_MB = 399
# TU ID DE TELEGRAM DENTRO DE LOS CORCHETES
OWNER = [983731245]

#PONGA AQUI PROXY ENCRIPTADO
proxy = 'KHGIJKYKJHLHFIYKKFIFCGYHJEKEEFRHCJLIDELF'

# CUENTA DE MEGA
# GMAIL DE CUENTA DE MEGA
GMAIL_MEGA = 'yanco148@gmail.com'
PASS_MEGA = 'yancarlos1482005'
