BOT_TOKEN = '5567257868:AAH2RS1EhqrXEIHwJU_jPjgJU-J_-PTUhIE'
API_ID = '17232014'
API_HASH = '5eb747e0b34842c90a32af2df2364e32'


# DATOS DEL MOODLE
#USUARIO DEL MOODLE entre las comillas
USUARIO = 'leonelmg'
#CONTRASEÑA DEL MOODLE entre las comillas
PASSWORD = 'Jose9101*'
#ID DEL MOODLE
USUARIO_ID = 7463
# PAGINA DEL MOODLE DEBE ESTAR COMO EL EJEMPLO: cursos.edu.uo.cu
MOODLE_URL = 'aula.ensap.sld.cu'
#TAMAÑO EN LO QUE SE PICARAN LOS ZIP AL SUBIR AL MOODLE
ZIP_MB = 399
# TU ID DE TELEGRAM DENTRO DE LOS CORCHETES
OWNER = [983731245]

#PONGA AQUI PROXY ENCRIPTADO
proxy = 'KHGIJKYKJHLHFIYKKFIFCGYHJEKEEFRHCJLIDELF'

# CUENTA DE MEGA
# GMAIL DE CUENTA DE MEGA
GMAIL_MEGA = 'yanco148@gmail.com'
PASS_MEGA = 'yancarlos1482005'
